[[drone]]
id = 1
connected_node_ids = [5, 6, 11]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [5, 6]
pdr = 0.03

[[drone]]
id = 3
connected_node_ids = [7, 8, 12]
pdr = 0.14

[[drone]]
id = 4
connected_node_ids = [7, 8, 12]
pdr = 0.14

[[drone]]
id = 5
connected_node_ids = [1, 2, 9]
pdr = 0.14

[[drone]]
id = 6
connected_node_ids = [1, 2, 10]
pdr = 0.30

[[drone]]
id = 7
connected_node_ids = [3, 4, 9]
pdr = 0.10

[[drone]]
id = 8
connected_node_ids = [3, 4, 10]
pdr = 0.14

[[drone]]
id = 9
connected_node_ids = [5, 7]
pdr = 0.50

[[drone]]
id = 10
connected_node_ids = [6, 8]
pdr = 0.25

[[client]]
id = 11
connected_drone_ids = [1]

[[server]]
id = 12
connected_drone_ids = [3, 4]