[[drone]]
id = 1
connected_node_ids = [2, 3, 11]
pdr = 0

# Layer 2
[[drone]]
id = 2
connected_node_ids = [1, 4, 5, 6]
pdr = 0

[[drone]]
id = 3
connected_node_ids = [1, 4, 5, 6]
pdr = 0

# Layer 3
[[drone]]
id = 4
connected_node_ids = [2, 3, 7, 8, 9, 10]
pdr = 0

[[drone]]
id = 5
connected_node_ids = [2, 3, 7, 8, 9, 10]
pdr = 0

[[drone]]
id = 6
connected_node_ids = [2, 3, 7, 8, 9, 10]
pdr = 0

# Layer 4
[[drone]]
id = 7
connected_node_ids = [4, 5, 6, 12]
pdr = 0

[[drone]]
id = 8
connected_node_ids = [4, 5, 6]
pdr = 0

[[drone]]
id = 9
connected_node_ids = [4, 5, 6]
pdr = 0

[[drone]]
id = 10
connected_node_ids = [4, 5, 6, 12]
pdr = 0

[[client]]
id = 11
connected_drone_ids = [1]

[[server]]
id = 12
connected_drone_ids = [7, 10]